### ISSUE TITLE
TAF Management App

### ISSUE THREAD

**Issue by danixeee** [openlawlibrary/taf#14]
Implement following features based on TAF Management App specification:

- [x] ~~Smart card integration (`oll-sc`) (#20)~~ use yubikey manager (#56)
- [x] Preview metadata file for given metadata name (#15)
- [x] Preview target file for given target name (#16)
- [x] List keys (certificates) for given metadata name (#17)
- [x] Add/Remove key & Edit certificate (#18)
- [x] Create and send certificate signing request (CSR) (#19)
