### ISSUE TITLE
Handling different states 

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#210]
### Necessary for TAF 1.0

- [x] #496

#### Different states in TAF could be:

```
args:
    - `--force` - force all repositories into consistent state at LVC and then run updater; may lose data. provide info on all changes made to repositories in order get to consistent state (use reflog if needed)


LVC = Last Validated Commit

axis:
    - working directory
        - clean  
            - happy path
        - ~dirty~
            - DEFAULT: FAIL
            - --force: git clean -fd; git reset HEAD --hard; proceed with update
    - branch
        - correct
            - happy path
        - incorrect branch or detached HEAD?
            - DEFAULT: stay on the incorrect branch; update correct branch; provide warning that not on the correct branch
            - --force: switch to LVC branch; proceed with update
    - commit
        - at last validated commit
            - happy path
        - validatable (in authentication chain, even if it is in "future" relative to last validated commit; this could happen if you manually pull or reset --hard)
            - DEFAULT: update to LVC; proceed with update
        - not validatable (not in validation chain)
            - DEFAULT: FAIL
            - --force: force branch to LVC; proceed with update
        - trailing unvalidated commits (in law-xml-codified but not law) - we call them unauthenticated in updater
            - DEFAULT: FAIL
            - --force: reset LVC --hard; proceed with update
    - local repositories (all commits are consistent at repository level)
        - doesn't exist, no commit
            - DEFAULT: create repo; ff to LVC
    - local vs remote
        - remote is consistent with local - no trailing unauthenticated commits
            - happy path
        - remote is consistent with local - trailing unauthenticated commits on remote 
            - DEFAULT: update to last validatable commit on remote; then fail for any unauthenticate commits on repos that don't allow; notify of commits on repos that do allow
        - remote is consistent with local - trailing unauthenticated commits on local
            - DEFAULT: update to the last authenticatable commit on remote; FAIL if repo does not allow trailing commits or do nothing if repo allows trailing commits
            - --force: remove trailing commits
        - remote is consistent with local - trailing unauthenticated commits conflict on repo that allows trailing commits
            - DEFAULT: update to the last authenticatable commit on remote; FAIL
            - --force: update to the last authenticatable commit on remote; remove local commits
        - remote is inconsistent with local (i.e. both remote and local are valid but diverge)
            - DEFAULT: update to the last authenticable commit on remote; FAIL
        - remote state is not authenticatable (metadata issues, versions, keys, signing, etc.)
            - DEFAULT: Update to last authenticatable remote commit; then FAIL

States to specifically address:
    - html repo has commit with no corresponding law commit (remote is not valid so: Update to last valid/authenticatable remote commit; then FAIL)
    - local repository has valid commits that aren't on remote (remote is not valid so: Update to last valid/authenticatable remote commit; then FAIL)

Update algorithm:

- prep for update
    - this is where we address:
        - working directory axis
        - branch axis
        - commit axis (excluding commits past LVC)
        - local repositories axis
    - Get all local repositories consistent at LVC (EXCEPTION: allow commits past LVC)
        - --force: do everything you possibly can to get them to that state, if can't then fail
        - DEFAULT: can use:
            - fast forward
            - git clone for repos that have been removed
            - allowed to have commits past LVC - they will be validated during update process or FAIL at that point
- update
    - this is where we address:
        - local vs remote axis
        - commits past LVC (from commit axis)
 ```

We need to make a reliable testing framework that covers all the states that repositories can be in.

Think through with what state is a result of .git operations fail

Linked issues
- [x] https://github.com/openlawlibrary/taf/issues/467
- [x] https://github.com/openlawlibrary/taf/issues/450
- [x] https://github.com/openlawlibrary/taf/issues/484
- [x] https://github.com/openlawlibrary/taf/issues/486

**Comment by renatav** [comment]
Notes from 6/6/2024

Run validator on every commit so can never have an invalid state pushed to upstream
repo modification commands MUST update LAC
taf repo [update|validate] --no-deps only validate this repo
taf repo [update|validate] --upstream validate remote as well as local
taf repo validate --no-targets only validate metadata
if any repo is dirty, terminate!
taf repo [update|validate] --force - sets auth repo to LAC; sets data repos to LAC
an auth/data repo doesn't have a commit corresponding to LAC.
this happens when something has seriously broken (reset upstream to remove commits, etc.)
to remove a universe of states:
make it impossible to push invalid repos
implement reversions
how do we address unauthenticated commits?
if we implement --force; eliminate invalid repos
local repos are consistent at/before LAC: taf repo update
local repos are inconsistent or auth repo not in LAC history: taf repo update --force
= upstream
- local
* last authenticated commit (LAC)

initial     local      local         remote
state       forced     update        update
            validate
# 0: happy path; everything is exactly where updater left it; there have been no new commits
ADDDD       ADDDD      ADDDD         ADDDD   
                                           
                                      
                                         
                            

                             
*====       *====      *====         *==== 
taf repo update should be a no-op
check remote Auth repo for updates
check remote Data repos for updates? only if --validate-remote flag
validate anything before LAC? NO
# 1: happy path; everything is exactly where updater left it; there have been new commits
```
ADDDD       ADDDD      ADDDD         ADDDD   
                                           
                                      
                                         
                            
*----       *----      *----             
                             
=====       =====      =====         *==== 
```

```
# 2: auth repo is somehow behind LAC; data repos are consistent with current state of auth repo
ADDDD       ADDDD      ADDDD         ADDDD    
                                           
-----       -----                     
                                         
                            
*           *          *----             
                             
=====       =====      =====         *==== 
```
taf repo update should work

```
ADDDD       ADDDD      ADDDD         ADDDD    [2: LAC is in auth repo's history; data repos are consistent with current state of auth repo]
*----      *----            
-????
=====       =====      =====         *====

```

```
ADDDD       ADDDD      ADDDD         ADDDD    [2: auth repo is somehow behind LAC; data repos are all over the place]
   --
-         -----                    
*          *----            
=====       =====      =====         *====
```
```
ADDDD       ADDDD      ADDDD         ADDDD   [state 2]
   --
*----      *----            
--
=====       =====      =====         *====
```
```
ADDDD       ADDDD      ADDDD         ADDDD   [state 3]
---       *----      *----            
=====       =====      =====         *====
```

taf repo update
   state 1: fail
   state 2: succeed
   state 3: succeed
taf repo update --force
   this must be used if data repos are out of sync with authentication repo
taf repo validate (edited)

**Comment by renatav** [comment]
![PXL_20240924_235203780](https://github.com/user-attachments/assets/8e674af8-bfe6-4f6b-b9a5-4e7df1a0329a)

**Comment by renatav** [comment]
I think that we can close this issue and create new ones to handle additional states as we discover bugs and figure out ways to improve this. `force` was implemented and it can be used to remove uncommitted changes, unpushed commits and start the validation from the beginning in cases when the repositories are out of sync. Partial update was also implemented, meaning that all repositories will be update up to the last valid commit. Additionally, the `force` flag can also be used to ensure that the newest branch will be checked out if a repository is in a detached head state or when an older branch was manually checked out. Errors no longer occur when a repo is in a detached head state, even when `force` is not specified.
